import Navbar from 'layout/header/navbar'
import '../styles/globals.scss'
import type {Metadata} from 'next'
import {DM_Sans, Oxygen_Mono} from 'next/font/google'

// primary font
const oxygenMono = Oxygen_Mono({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-primary',
})

// Secondary font
const DmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-secondary',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${DmSans.className} ${DmSans.variable} ${oxygenMono.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
